<?php
// Code trong header.php để hiển thị giỏ hàng
$isLoggedIn = isset($_SESSION['user']);

// Nếu người dùng đã đăng nhập, đảm bảo giỏ hàng từ database đã được tải
if (isset($_SESSION['user']) && !isset($_SESSION['cart_loaded'])) {
    // Load giỏ hàng từ database nếu chưa được tải
    require_once('Models/CartModel.php');
    $cartModel = new CartModel();
    $userId = $_SESSION['user']['id_User'];
    $userCart = $cartModel->getUserCart($userId);
    
    // Cập nhật giỏ hàng trong session
    $_SESSION['cart'] = [];
    foreach ($userCart as $item) {
        $itemKey = $item['id_Product'] . '_' . $item['size'];
        $_SESSION['cart'][$itemKey] = [
            'product_id' => $item['id_Product'],
            'quantity' => $item['quantity'],
            'size' => $item['size']
        ];
    }
    
    // Đánh dấu giỏ hàng đã được tải
    $_SESSION['cart_loaded'] = true;
}

// Lấy số lượng sản phẩm từ session giỏ hàng
$cart = $_SESSION['cart'] ?? [];
$totalItems = 0;
foreach ($cart as $item) {
    $totalItems += $item['quantity'];
}

// Lấy thông tin cài đặt từ CSDL
require_once 'Controllers/FooterController.php';
$footerController = new FooterController();
$storeSettings = $footerController->getStoreSettings();

// Lấy đường dẫn logo và tên website
$logoPath = !empty($storeSettings['logo_path']) ? $storeSettings['logo_path'] : '/Project_Website/ProjectWeb/upload/img/Header/logo.png';
$siteName = !empty($storeSettings['site_name']) ? $storeSettings['site_name'] : 'RS Store';
?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($siteName) ?> - Thời trang nam chính hãng</title>
    
    <!-- Trong thẻ <head> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/Project_Website/ProjectWeb/layout/css/Header.css"> <!-- Đường dẫn đến file CSS mới -->
    
       
</head>
<body>
        <!-- Top promotional banner -->
        <div class="top-banner">
        <div class="top-banner-carousel">
            <!-- Banner items will be dynamically generated by JavaScript -->
        </div>
    </div>
    <!-- Header -->
    <header>
        <div class="container-fluid">
            <div class="row py-2 main-header align-items-center">
                <!-- Mobile menu toggle -->
                <div class="col-2 d-lg-none">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                </div>
                
                <!-- Logo for Mobile -->
                <div class="col-6 d-md-none text-center text-md-start">
                    <a href="/ProjectWeb/index.php" class="logo">
                        <img src="<?= htmlspecialchars($logoPath) ?>" alt="<?= htmlspecialchars($siteName) ?> Logo" class="img-fluid">
                    </a>
                </div>
                
                <!-- Combined Logo, Brand Text, and Search bar for MD and UP -->
                <div class="col-md-8 col-lg-9 d-none d-md-flex align-items-center">
                    <a href="/ProjectWeb/index.php" class="logo me-2 d-none d-md-inline-block">
                        <img src="<?= htmlspecialchars($logoPath) ?>" alt="<?= htmlspecialchars($siteName) ?> Logo" class="img-fluid desktop-logo-img">
                    </a>
                    <h1 class="rs-store-brand-text me-3 h5 mb-0 d-none d-md-inline-block"><?= htmlspecialchars($siteName) ?></h1>
                        <div class="search-container flex-grow-1 position-relative">
                        <form action="index.php" method="get" id="searchForm">
                            <input type="hidden" name="controller" value="search">
                            <input type="text" 
                                   placeholder="Tìm theo tên sản phẩm, tag..." 
                                   name="q" 
                                   class="search-input" 
                                   id="searchInput"
                                   autocomplete="off">
                            <button type="submit" class="search-button">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>
                        
                        <!-- Search Suggestions Dropdown -->
                        <div class="search-suggestions" id="searchSuggestions" style="display: none;">
                            <div class="suggestions-header">
                                <i class="fas fa-search"></i> Gợi ý tìm kiếm
                            </div>
                            <div class="suggestions-content" id="suggestionsContent">
                                <!-- Suggestions will be populated by JavaScript -->
                            </div>
                        </div>
                    </div>
                    
                    <!-- Mobile search bar version -->
                    <div class="container-fluid d-md-none py-2 mobile-search">
                        <div class="search-container position-relative">
                            <form action="index.php" method="get" id="mobileSearchForm">
                                <input type="hidden" name="controller" value="search">
                                <input type="text" 
                                       placeholder="Tìm theo tên sản phẩm, tag..." 
                                       name="q" 
                                       class="search-input" 
                                       id="mobileSearchInput"
                                       autocomplete="off">
                                <button type="submit" class="search-button">
                                    <i class="fas fa-search"></i>
                                </button>
                            </form>
                            
                            <!-- Mobile Search Suggestions -->
                            <div class="search-suggestions" id="mobileSearchSuggestions" style="display: none;">
                                <div class="suggestions-header">
                                    <i class="fas fa-search"></i> Gợi ý tìm kiếm
                                </div>
                                <div class="suggestions-content" id="mobileSuggestionsContent">
                                    <!-- Suggestions will be populated by JavaScript -->
                                </div>
                            </div>
                        </div>
                    </div>

    <style>
        /* Search Suggestions Styling */
        .search-suggestions {
            position: absolute;
            top: 100%;
            left: 0;
            right: 0;
            background: white;
            border: 1px solid #ddd;
            border-top: none;
            border-radius: 0 0 8px 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            z-index: 1000;
            max-height: 400px;
            overflow-y: auto;
        }
        
        .suggestions-header {
            padding: 0.75rem 1rem;
            background: #f8f9fa;
            font-weight: 600;
            color: #666;
            font-size: 0.9rem;
            border-bottom: 1px solid #eee;
        }
        
        .suggestion-item {
            padding: 0.75rem 1rem;
            cursor: pointer;
            border-bottom: 1px solid #f0f0f0;
            transition: background-color 0.2s ease;
            display: flex;
            align-items: center;
        }
        
        .suggestion-item:hover {
            background-color: #f8f9fa;
        }
        
        .suggestion-item:last-child {
            border-bottom: none;
        }
        
        .suggestion-image {
            width: 40px;
            height: 40px;
            object-fit: cover;
            border-radius: 4px;
            margin-right: 0.75rem;
        }
        
        .suggestion-info {
            flex-grow: 1;
        }
        
        .suggestion-name {
            font-weight: 500;
            color: #333;
            margin-bottom: 0.25rem;
            font-size: 0.9rem;
        }
        
        .suggestion-price {
            color: #e74c3c;
            font-weight: 600;
            font-size: 0.85rem;
        }
        
        .no-suggestions {
            padding: 1rem;
            text-align: center;
            color: #999;
            font-style: italic;
        }
        
        .search-loading {
            padding: 1rem;
            text-align: center;
            color: #666;
        }
        
        /* Loading animation */
        .search-loading::after {
            content: '';
            display: inline-block;
            width: 20px;
            height: 20px;
            margin-left: 0.5rem;
            border: 2px solid #f3f3f3;
            border-top: 2px solid #333;
            border-radius: 50%;
            animation: spin 1s linear infinite;
        }
        
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        
        /* Mobile specific styles */
        @media (max-width: 767px) {
            .search-suggestions {
                left: 1rem;
                right: 1rem;
            }
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Initialize search functionality for both desktop and mobile
            initializeSearch('searchInput', 'searchSuggestions', 'suggestionsContent');
            initializeSearch('mobileSearchInput', 'mobileSearchSuggestions', 'mobileSuggestionsContent');
            
            function initializeSearch(inputId, suggestionsId, contentId) {
                const searchInput = document.getElementById(inputId);
                const searchSuggestions = document.getElementById(suggestionsId);
                const suggestionsContent = document.getElementById(contentId);
                
                if (!searchInput || !searchSuggestions || !suggestionsContent) return;
                
                let searchTimeout;
                let isSearching = false;
                
                // Search input event listener
                searchInput.addEventListener('input', function() {
                    const query = this.value.trim();
                    
                    clearTimeout(searchTimeout);
                    
                    if (query.length < 2) {
                        hideSuggestions();
                        return;
                    }
                    
                    // Show loading state
                    showLoading();
                    
                    // Debounce search requests
                    searchTimeout = setTimeout(() => {
                        fetchSuggestions(query);
                    }, 300);
                });
                
                // Hide suggestions when clicking outside
                document.addEventListener('click', function(e) {
                    if (!searchInput.contains(e.target) && !searchSuggestions.contains(e.target)) {
                        hideSuggestions();
                    }
                });
                
                // Handle keyboard navigation
                searchInput.addEventListener('keydown', function(e) {
                    const suggestions = searchSuggestions.querySelectorAll('.suggestion-item');
                    const activeIndex = Array.from(suggestions).findIndex(item => 
                        item.classList.contains('active')
                    );
                    
                    switch(e.key) {
                        case 'ArrowDown':
                            e.preventDefault();
                            if (activeIndex < suggestions.length - 1) {
                                setActiveSuggestion(suggestions, activeIndex + 1);
                            }
                            break;
                        case 'ArrowUp':
                            e.preventDefault();
                            if (activeIndex > 0) {
                                setActiveSuggestion(suggestions, activeIndex - 1);
                            }
                            break;
                        case 'Enter':
                            const activeItem = suggestions[activeIndex];
                            if (activeItem) {
                                e.preventDefault();
                                activeItem.click();
                            }
                            break;
                        case 'Escape':
                            hideSuggestions();
                            break;
                    }
                });
                
                function fetchSuggestions(query) {
                    if (isSearching) return;
                    
                    isSearching = true;
                    
                    fetch(`index.php?controller=search&action=suggestions&q=${encodeURIComponent(query)}`)
                        .then(response => response.json())
                        .then(data => {
                            displaySuggestions(data);
                            isSearching = false;
                        })
                        .catch(error => {
                            console.error('Search error:', error);
                            hideSuggestions();
                            isSearching = false;
                        });
                }
                
                function displaySuggestions(suggestions) {
                    if (suggestions.length === 0) {
                        suggestionsContent.innerHTML = '<div class="no-suggestions">Không tìm thấy sản phẩm phù hợp</div>';
                    } else {
                        const html = suggestions.map(item => `
                            <div class="suggestion-item" onclick="selectProduct(${item.id_product})">
                                <img src="/Project_Website/ProjectWeb/upload/img/All-Product/${item.main_image}" 
                                     alt="${escapeHtml(item.name)}" 
                                     class="suggestion-image"
                                     onerror="this.src='/Project_Website/ProjectWeb/upload/img/All-Product/default.jpg'">
                                <div class="suggestion-info">
                                    <div class="suggestion-name">${escapeHtml(item.name)}</div>
                                    <div class="suggestion-price">${formatPrice(item.current_price)}₫</div>
                                </div>
                            </div>
                        `).join('');
                        suggestionsContent.innerHTML = html;
                    }
                    
                    showSuggestions();
                }
                
                function showLoading() {
                    suggestionsContent.innerHTML = '<div class="search-loading">Đang tìm kiếm...</div>';
                    showSuggestions();
                }
                
                function showSuggestions() {
                    searchSuggestions.style.display = 'block';
                }
                
                function hideSuggestions() {
                    searchSuggestions.style.display = 'none';
                }
                
                function setActiveSuggestion(suggestions, index) {
                    suggestions.forEach(item => item.classList.remove('active'));
                    if (suggestions[index]) {
                        suggestions[index].classList.add('active');
                    }
                }
            }
            
            // Global functions
            window.selectProduct = function(productId) {
                window.location.href = `index.php?controller=product&action=show&id=${productId}`;
            };
            
            window.escapeHtml = function(text) {
                const div = document.createElement('div');
                div.textContent = text;
                return div.innerHTML;
            };
            
            window.formatPrice = function(price) {
                return parseInt(price).toLocaleString('vi-VN');
            };
        });
    </script>
                </div>
                
                <!-- User actions -->
                <div class="col-md-4 col-lg-3 col-4">
                    <div class="d-flex justify-content-end">
                        <!-- User account -->
                      <!-- User account -->
                      <!-- User account -->
                       <div class="header-action me-3 position-relative d-flex align-items-center">
                            <?php if ($isLoggedIn): ?>
                                <!-- Hiển thị thông tin người dùng đã đăng nhập -->
                                <a href="index.php?controller=account" class="action-link d-flex align-items-center">
                                    <i class="fas fa-user me-1"></i>
                                    <span class="d-none d-lg-inline-block"><?= $_SESSION['user']['name'] ?></span>
                                </a>
                                <a href="index.php?controller=login&action=logout" class="action-link small ms-2 d-flex align-items-center">
                                    <i class="fas fa-sign-out-alt me-1"></i>
                                    <span>Đăng Xuất</span>
                                </a>
                            <?php else: ?>
                                <!-- Hiển thị link đơn giản cho người dùng chưa đăng nhập -->
                                <a href="index.php?controller=login" class="action-link d-flex align-items-center">
                                    <i class="fas fa-user me-1"></i>
                                    <span class="d-none d-lg-inline-block">Tài khoản</span>
                                </a>
                            <?php endif; ?>
                        </div>

                        <?php if ($isLoggedIn): ?>
                            <div class="header-action position-relative dropdown">
                                <a href="index.php?controller=cart&action=index" class="action-link cart-toggle" id="cartBtn">
                                    <i class="fas fa-shopping-cart"></i>
                                    <span class="cart-count" id="item-count"><?= $totalItems ?? 0; ?></span>
                                    <span class="d-none d-lg-inline-block">Giỏ hàng</span>
                                </a>
                                <!-- Dropdown content... -->
                            </div>
                        <?php endif; ?>
                        <!-- Shopping cart -->
                        <!-- <div class="header-action position-relative dropdown">
                              <a href="index.php?controller=cart&action=index" class="action-link cart-toggle" id="cartBtn">
                                    <i class="fas fa-shopping-cart"></i>
                                    <span class="cart-count" id="item-count"><?=$totalItems; ?></span>
                                    <span class="d-none d-lg-inline-block">Giỏ hàng</span>
                             </a>
                            <div class="cart-dropdown dropdown-menu">
                                <div class="dropdown-content">
                                    <div class="dropdown-header">
                                        <h5>Giỏ hàng</h5>
                                    </div>
                                    <div class="dropdown-body">
                                        <?php if (empty($cart)): ?>
                                            <div class="empty-cart text-center">
                                                <img src="/ProjectWeb/upload/img/Header/no-cart.png" alt="Empty Cart" class="img-fluid mb-3">
                                                <p>Hiện chưa có sản phẩm</p>
                                            </div>
                                        <?php else: ?>
                                            <div class="cart-items">
                                                <?php 
                                                $cartTotal = 0;
                                                foreach ($cart as $item):
                                                    $productId = $item['product_id'];
                                                    // Tạo một đối tượng ProductModel để lấy thông tin sản phẩm
                                                    require_once('Models/ProductModel.php');
                                                    $productModel = new ProductModel();
                                                    $product = $productModel->findById($productId);
                                                    if ($product):
                                                        $subtotal = $product['current_price'] * $item['quantity'];
                                                        $cartTotal += $subtotal;
                                                ?>
                                                    <div class="cart-item d-flex mb-2">
                                                        <img src="/Project_Website/ProjectWeb/upload/img/All-Product/<?= $product['main_image'] ?>" alt="<?= $product['name'] ?>" class="cart-item-image me-2" style="width: 50px; height: 50px; object-fit: cover;">
                                                        <div class="cart-item-details flex-grow-1">
                                                            <div class="cart-item-title"><?= $product['name'] ?></div>
                                                            <div class="d-flex justify-content-between">
                                                                <span class="cart-item-quantity"><?= $item['quantity'] ?> x</span>
                                                                <span class="cart-item-price"><?= number_format($product['current_price'], 0, ',', '.') ?>₫</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php 
                                                    endif;
                                                endforeach; 
                                                ?>
                                            </div>
                                            <div class="cart-summary">
                                                <div class="d-flex justify-content-between mb-2">
                                                    <span>Tạm tính:</span>
                                                    <span><?= number_format($cartTotal, 0, ',', '.') ?>₫</span>
                                                </div>
                                                <div class="d-flex justify-content-between fw-bold mb-3">
                                                    <span>Tổng tiền:</span>
                                                    <span><?= number_format($cartTotal, 0, ',', '.') ?>₫</span>
                                                </div>
                                                <div class="d-flex justify-content-between">
                                                    <a href="index.php?controller=cart&action=index" class="btn btn-outline-dark">Giỏ hàng</a>
                                                    <a href="index.php?controller=order" class="btn btn-dark">Thanh toán</a>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Mobile search bar -->
        <div class="container-fluid d-md-none py-2 mobile-search">
            <div class="search-container">
                <form action="/ProjectWeb/index.php?controller=search" method="get">
                    <input type="text" placeholder="Bạn đang tìm gì..." name="q" class="search-input">
                    <button type="submit" class="search-button">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>

        <!-- Navigation menu -->
      <div class="main-nav">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="collapse navbar-collapse" id="navbarMain">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="index.php">
                                    <i class="fas fa-home me-1"></i>TRANG CHỦ
                                </a>
                            </li>
                            <?php 
                            // Khởi tạo controller để lấy danh mục
                            require_once('Controllers/CategoryController.php');
                            $categoryController = new CategoryController();
                            $categories = $categoryController->getHeaderCategories();
                            
                            // Hiển thị các danh mục từ database
                            foreach($categories as $category): 
                                // Chỉ hiển thị các danh mục không bị ẩn (hide = 0 hoặc NULL)
                                if(!isset($category['hide']) || $category['hide'] == 0):
                            ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?='index.php?controller=category&action=show&id='.$category['id_Category'] ?>">
                                        <?= strtoupper($category['name']) ?>
                                    </a>
                                </li>
                            <?php 
                                endif;
                            endforeach; 
                            ?>
                           
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>
    </header>

    <!-- Main content placeholder -->
    <main>
        <!-- Main content will go here -->
         
    </main>

    <!-- Notification container -->
    <div class="notification-container"></div>

    <!-- Forgot Password Modal -->
    <div class="modal fade" id="forgotPasswordModal" tabindex="-1" aria-labelledby="forgotPasswordModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="forgotPasswordModalLabel">Khôi phục mật khẩu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Vui lòng nhập email hoặc số điện thoại để khôi phục mật khẩu</p>
                    <div class="mb-3">
                        <input type="text" class="form-control" id="recoveryContact" 
                               placeholder="Email hoặc số điện thoại" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" id="recoverButton">Gửi mã xác nhận</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Cuối thẻ <body> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/Project_Website/ProjectWeb/layout/js/Header.js"></script> <!-- Đường dẫn đến file JS mới -->
    <!-- Thêm script để xử lý header khi cuộn -->
    <script>
        document.addEventListener("cartUpdated", function () {
    const countElement = document.getElementById("item-count");
    if (countElement) {
        const cartCount = sessionStorage.getItem("cartCount") || 0;
        countElement.textContent = cartCount;
    }
});
        document.addEventListener('DOMContentLoaded', function() {
    // Lấy thông tin giỏ hàng mới nhất từ server
    fetch("index.php?controller=cart&action=getCount", {
        method: "GET",
        headers: {
            "Content-Type": "application/json",
            "X-Requested-With": "XMLHttpRequest",
        },
    })
    .then(response => response.json())
    .then(data => {
        // Cập nhật số lượng sản phẩm trong giỏ hàng
        sessionStorage.setItem("cartCount", data.count);
        
        // Cập nhật hiển thị số lượng
        const countElement = document.getElementById("item-count");
        if (countElement) {
            countElement.textContent = data.count;
        }
        
        // Thông báo cho các thành phần khác rằng giỏ hàng đã được cập nhật
        document.dispatchEvent(new CustomEvent("cartUpdated"));
    })
    .catch(error => {
        console.error("Lỗi khi lấy dữ liệu giỏ hàng:", error);
    });
});
        window.addEventListener('scroll', function() {
            const header = document.querySelector('header');
            if (window.scrollY > 100) {
                header.classList.add('scrolled');
            } else {
                header.classList.remove('scrolled');
            }
        });

        // Xử lý form quên mật khẩu
        document.addEventListener('DOMContentLoaded', function() {
            const forgotPasswordLink = document.getElementById('forgotPasswordLink');
            const forgotPasswordModal = document.getElementById('forgotPasswordModal');
            
            if (forgotPasswordLink && forgotPasswordModal) {
                forgotPasswordLink.addEventListener('click', function(e) {
                    e.preventDefault();
                    const modalInstance = new bootstrap.Modal(forgotPasswordModal);
                    modalInstance.show();
                });
            }
            
            // Xử lý nút gửi mã xác nhận
            const recoverButton = document.getElementById('recoverButton');
            if (recoverButton) {
                recoverButton.addEventListener('click', function() {
                    const recoveryContact = document.getElementById('recoveryContact').value.trim();
                    
                    if (!recoveryContact) {
                        alert('Vui lòng nhập email hoặc số điện thoại');
                        return;
                    }
                    
                    // Gửi AJAX request đến forgotPassword
                    fetch('index.php?controller=login&action=forgotPassword', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded',
                        },
                        body: 'contact=' + encodeURIComponent(recoveryContact)
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            // Ẩn modal
                            const modalInstance = bootstrap.Modal.getInstance(forgotPasswordModal);
                            modalInstance.hide();
                            
                            // Hiển thị thông báo thành công
                            alert(data.message);
                        } else {
                            // Hiển thị thông báo lỗi
                            alert(data.message);
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        alert('Đã xảy ra lỗi. Vui lòng thử lại sau.');
                    });
                });
            }
        });
        
    </script>
</body>
</html>
<!-- Navigation menu -->