<?php
// Đoạn code này thêm vào header.php

// Lấy số lượng sản phẩm từ session giỏ hàng
$cart = $_SESSION['cart'] ?? [];
$totalItems = 0;
foreach ($cart as $item) {
    $totalItems += $item['quantity'];
}

// Đoạn mã JavaScript để khởi tạo số lượng sản phẩm trong giỏ hàng
echo "<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Lưu số lượng sản phẩm vào sessionStorage
        sessionStorage.setItem('cartCount', '{$totalItems}');
        
        // Cập nhật hiển thị số lượng
        const countElement = document.getElementById('item-count');
        if (countElement) {
            countElement.textContent = '{$totalItems}';
        }
    });
</script>";
?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RSStore - Thời trang nam chính hãng</title>


       
    
    <!-- Trong thẻ <head> -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/Project_Website/ProjectWeb/layout/css/Header.css"> <!-- Đường dẫn đến file CSS mới -->
    
       
</head>
<body>
        <!-- Top promotional banner -->
        <div class="top-banner">
        <div class="top-banner-carousel">
            <!-- Banner items will be dynamically generated by JavaScript -->
        </div>
    </div>
    <!-- Header -->
    <header>
        <div class="container-fluid">
            <div class="row py-2 main-header align-items-center">
                <!-- Mobile menu toggle -->
                <div class="col-2 d-lg-none">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                </div>
                
                <!-- Logo for Mobile -->
                <div class="col-6 d-md-none text-center text-md-start">
                    <a href="/ProjectWeb/index.php" class="logo">
                        <img src="/Project_Website/ProjectWeb/upload/img/Header/logo.png" alt="RSStore Logo" class="img-fluid">
                    </a>
                </div>
                
                <!-- Combined Logo, Brand Text, and Search bar for MD and UP -->
                <div class="col-md-8 col-lg-9 d-none d-md-flex align-items-center">
                    <a href="/ProjectWeb/index.php" class="logo me-2 d-none d-md-inline-block">
                        <img src="/Project_Website/ProjectWeb/upload/img/Header/logo.png" alt="RSStore Logo" class="img-fluid desktop-logo-img">
                    </a>
                    <h1 class="rs-store-brand-text me-3 h5 mb-0 d-none d-md-inline-block">RS Store</h1>
                    <div class="search-container flex-grow-1">
                        <form action="/ProjectWeb/index.php?controller=search" method="get">
                            <input type="text" placeholder="Bạn đang tìm gì..." name="q" class="search-input">
                            <button type="submit" class="search-button">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>
                    </div>
                </div>
                
                <!-- User actions -->
                <div class="col-md-4 col-lg-3 col-4">
                    <div class="d-flex justify-content-end">
                        <!-- User account -->
                        <div class="header-action me-3 position-relative dropdown">
                            <a href="javascript:void(0);" class="action-link account-toggle" id="userAccountBtn">
                                <i class="fas fa-user"></i>
                                <span class="d-none d-lg-inline-block">Tài khoản</span>
                            </a>
                            <div class="account-dropdown dropdown-menu">
                                <div class="dropdown-content">
                                    <div class="dropdown-header">
                                        <h5>Đăng nhập tài khoản</h5>
                                    </div>
                                    <div class="dropdown-body">
                                        <form action="/ProjectWeb/index.php?controller=auth&action=login" method="post">
                                            <div class="form-group mb-3">
                                                <input type="email" class="form-control" placeholder="Email" required>
                                            </div>
                                            <div class="form-group mb-3">
                                                <input type="password" class="form-control" placeholder="Mật khẩu" required>
                                            </div>
                                            <div class="d-grid gap-2">
                                                <button type="submit" class="btn btn-dark">Đăng nhập</button>
                                            </div>
                                        </form>
                                        <div class="mt-3 text-center">
                                            <p class="mb-1">Khách hàng mới? <a href="/ProjectWeb/index.php?controller=auth&action=register">Tạo tài khoản</a></p>
                                            <p class="mb-0"><a href="/ProjectWeb/index.php?controller=auth&action=forgot">Quên mật khẩu?</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                 

                        <!-- Shopping cart -->
                        <div class="header-action position-relative dropdown">
                            <a href="index.php?controller=cart&action=index" class="action-link cart-toggle" id="cartBtn">
                                <i class="fas fa-shopping-cart"></i>
                             
                                <span class="cart-count" id="item-count"><?php echo $totalItems; ?></span>
                                <span  class="d-none d-lg-inline-block">Giỏ hàng</span>
                            </a>
                            <div class="cart-dropdown dropdown-menu">
                                <div class="dropdown-content">
                                    <div class="dropdown-header">
                                        <h5>Giỏ hàng</h5>
                                    </div>
                                    <div class="dropdown-body">
                                        <div class="empty-cart text-center">
                                            <img src="/ProjectWeb/upload/img/Header/no-cart.png" alt="Empty Cart" class="img-fluid mb-3">
                                            <p>Hiện chưa có sản phẩm</p>
                                        </div>
                                        <div class="cart-summary" style="display: none;">
                                            <div class="d-flex justify-content-between mb-2">
                                                <span>Tạm tính:</span>
                                                <span>0₫</span>
                                            </div>
                                            <div class="d-flex justify-content-between mb-2">
                                                <span>Giảm giá:</span>
                                                <span>0₫</span>
                                            </div>
                                            <div class="d-flex justify-content-between fw-bold mb-3">
                                                <span>Tổng tiền:</span>
                                                <span>0₫</span>
                                            </div>
                                            <div class="d-flex justify-content-between">
                                                <a href="/ProjectWeb/index.php?controller=cart" class="btn btn-outline-dark">Giỏ hàng</a>
                                                <a href="/ProjectWeb/index.php?controller=checkout" class="btn btn-dark">Thanh toán</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Mobile search bar -->
        <div class="container-fluid d-md-none py-2 mobile-search">
            <div class="search-container">
                <form action="/ProjectWeb/index.php?controller=search" method="get">
                    <input type="text" placeholder="Bạn đang tìm gì..." name="q" class="search-input">
                    <button type="submit" class="search-button">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>

        <!-- Navigation menu -->
      <div class="main-nav">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="collapse navbar-collapse" id="navbarMain">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="index.php">
                                    <i class="fas fa-home me-1"></i>TRANG CHỦ
                                </a>
                            </li>
                            <?php 
                            // Khởi tạo controller để lấy danh mục
                            require_once('Controllers/CategoryController.php');
                            $categoryController = new CategoryController();
                            $categories = $categoryController->getHeaderCategories();
                            
                            // Hiển thị các danh mục từ database
                            foreach($categories as $category): 
                                // Chỉ hiển thị các danh mục không bị ẩn (hide = 0 hoặc NULL)
                                if(!isset($category['hide']) || $category['hide'] == 0):
                            ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?='index.php?controller=category&action=show&id='.$category['id_Category'] ?>">
                                        <?= strtoupper($category['name']) ?>
                                    </a>
                                </li>
                            <?php 
                                endif;
                            endforeach; 
                            ?>
                           
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>
    </header>

    <!-- Main content placeholder -->
    <main>
        <!-- Main content will go here -->
         
    </main>

    <!-- Notification container -->
    <div class="notification-container">
        
     </div>

    <!-- Cuối thẻ <body> -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/Project_Website/ProjectWeb/layout/js/Header.js"></script> <!-- Đường dẫn đến file JS mới -->
    <!-- Thêm script để xử lý header khi cuộn -->
    <script>
        window.addEventListener('scroll', function() {
            const header = document.querySelector('header');
            if (window.scrollY > 100) {
                header.classList.add('scrolled');
            } else {
                header.classList.remove('scrolled');
            }
        });
    </script>
</body>
</html>
<!-- Navigation menu -->
